[package]
name = "rust_civit_comfy_bindings"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_civit_comfy_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
